### ISSUE TITLE
Github Pages Deployment

### ISSUE THREAD

**Issue by pourmand1376** [rohandebsarkar/academic-folio#16]
Hi, Unfortunately, `netlify` service is censored in my country. Is there any problem with github pages? Why not have them both?

**Comment by pourmand1376** [comment]
I see that the workflow you have is much better than github. I suggest that we only enable github but do not use it by default if possible.

**Comment by rohandebsarkar** [comment]
Sorry, I was not aware of the fact that netlify might be censored. The main reason I switched from GitHub pages was that since I host `al-folio` in my username domain, there are some things I can't test for this theme. Like I haven't yet set favicons but it gets favicons from `al-folio`, also I can't test 404 pages, etc.

**Comment by pourmand1376** [comment]
It is okay. I have found some working VPN for now. But, we should add this later.

**Comment by rohandebsarkar** [comment]
I tried using vercel instead of netlify, but vercel doesn't yet support hugo dependencies.

**Comment by rohandebsarkar** [comment]
https://rohandebsarkar.github.io/academic-folio/
